version: '3'
services:
  cicd-redis-test:
    image: redis:6
    container_name: cicd-redis-test
    ports:
      - ${REDIS_TEST_PORT}:6379
    env_file:
      - .env
    volumes:
      - test_redis_data:/data  # 挂载卷到 /data 目录
    environment:
      - TZ=Asia/Shanghai  # 设置时区为东8区

  cicd-mysql-test:
    image: mysql:8.0
    container_name: cicd-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SQL_MODE: "STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
      TZ: "Asia/Shanghai"
    ports:
      - 23306:3306
    volumes:
      - test_mysql_data:/var/lib/mysql  # 挂载卷到 MySQL 数据目录
      - './mysql-entrypoint/:/docker-entrypoint-initdb.d/'  # 挂载初始化脚本目录
    env_file:
      - .env
    command: --default-authentication-plugin=mysql_native_password  # 设置默认身份验证插件
volumes:
  test_redis_data:  # 定义 Redis 数据卷
  test_mysql_data:   # 定义 MySQL 数据卷